/* Edit the case files and certificate records below as you add verified evidence. */
const cases = [
  {id:'brute-force',number:'OP-001',symbol:'⌁',title:'Brute-Force Investigation',summary:'Tracing suspicious login attempts and source IPs through authentication logs to identify repeated access attempts.',tools:['Authentication logs','Splunk / log analysis','Source IP review'],why:'To practice separating routine login failures from patterns consistent with password guessing.',objective:'Identify repeated failed logins, investigate originating IPs and determine whether the observed activity warrants escalation.',actions:['Reviewed authentication failures and grouped events by source IP, target account and time window.','Looked for bursts of failed logins and possible successful authentication following failures.','Recorded relevant timestamps, accounts and source addresses for an investigation summary.'],skills:'Authentication-log interpretation, event correlation, IOC contextualization and escalation documentation.',outcome:'Lab exercise documented in the supplied CV: traced suspicious login attempts and source IPs to identify brute-force activity. Exact log exports and screenshots are pending publication.',relevance:'Common SOC authentication alerts require analysts to distinguish malicious guessing from user error and provide actionable context.',evidence:'Add redacted authentication log screenshot, Splunk query/export, case write-up and lab-room link.'},
  {id:'powershell',number:'OP-002',symbol:'>_',title:'PowerShell Attack Investigation',summary:'Correlating Windows events to examine suspicious PowerShell execution and identify potentially malicious command activity.',tools:['Windows event logs','PowerShell','Sysmon / endpoint telemetry'],why:'PowerShell is widely used by administrators and attackers; suspicious execution needs context rather than assumptions.',objective:'Reconstruct the sequence of suspicious PowerShell activity using relevant Windows telemetry.',actions:['Examined process and PowerShell-related event records for unusual execution.','Correlated execution time and surrounding endpoint activity to understand the command context.','Captured indicators and summarized why the observed behavior warranted review.'],skills:'Windows event analysis, process-chain reasoning and endpoint investigation.',outcome:'CV-reported lab investigation of suspicious PowerShell activity using correlated Windows events. Command samples and event IDs should be added from the actual exercise.',relevance:'Endpoint alerts often depend on understanding legitimate versus suspicious scripting behavior.',evidence:'Add sanitized event screenshot, process tree, command analysis, investigation notes and lab link.'},
  {id:'dns-pharming',number:'OP-003',symbol:'◇',title:'DNS Pharming Detection',summary:'Investigating suspicious DNS redirection by checking unexpected domain-to-IP mappings and poisoned DNS responses.',tools:['DNS analysis','Wireshark / packet review','Domain/IP investigation'],why:'DNS manipulation can redirect users without changing the address they typed, making response validation important.',objective:'Identify anomalous DNS responses and investigate unexpected destination IP addresses.',actions:['Inspected DNS response data for suspicious or inconsistent domain-to-IP resolution.','Compared observed mappings with the expected destination in the lab scenario.','Documented indicators suggesting DNS response manipulation.'],skills:'DNS protocol reasoning, packet inspection and network IOC investigation.',outcome:'CV-reported investigation of malicious DNS redirection and suspicious domain-to-IP mappings. Packet capture evidence is not yet linked.',relevance:'Network-focused SOC analysis uses DNS anomalies to identify possible redirection, compromise or malicious infrastructure.',evidence:'Add redacted PCAP screenshot, DNS comparison, investigation write-up and source lab link.'},
  {id:'lateral-movement',number:'OP-004',symbol:'⇢',title:'Lateral Movement Tracing',summary:'Correlating authentication and remote-access activity to trace suspicious movement between networked systems.',tools:['Windows/Linux authentication events','Remote access logs','MITRE ATT&CK'],why:'Individual login events may look ordinary until combined into a sequence across hosts.',objective:'Build a defensible timeline of suspicious cross-system access and identify the affected hosts/accounts.',actions:['Reviewed authentication and remote-access records from networked systems.','Correlated accounts, source/destination hosts and event timestamps.','Summarized the suspected movement path and its investigative significance.'],skills:'Cross-host event correlation, timeline reconstruction and ATT&CK-aligned investigation.',outcome:'CV-reported lab exercise tracing attacker movement using authentication and remote-access activity. Full timeline and host diagram are pending.',relevance:'Cross-endpoint correlation helps SOC teams recognize movement after an initial compromise.',evidence:'Add sanitized timeline, host diagram, event excerpts and lab link.'},
  {id:'mini-soc',number:'PRJ-001',symbol:'⌘',title:'Mini SOC Lab — SIEM Threat Detection',summary:'A practice environment that brings Windows and Linux security telemetry into Splunk for event review and ATT&CK mapping.',tools:['Splunk','Sysmon','Windows','Linux','MITRE ATT&CK'],why:'To move from isolated exercises to a connected environment where endpoint telemetry can be collected and investigated.',objective:'Centralize multi-OS security events, examine endpoint activity and connect meaningful observations to ATT&CK techniques.',actions:['Integrated Windows and Linux endpoints with Splunk as described in the CV.','Collected Windows endpoint telemetry with Sysmon.','Correlated relevant security events and mapped observed behavior to MITRE ATT&CK.'],skills:'SIEM data ingestion, endpoint visibility, event correlation and security model mapping.',outcome:'CV-listed mini SOC lab. A validated topology, ingestion screenshots, detection examples and repository should be published as evidence.',relevance:'A multi-source SIEM workflow approximates the data collection and triage process of a SOC.',evidence:'Add actual lab topology, Splunk ingestion screenshots, Sysmon events, SPL searches, setup notes and repository.'}
];
const certifications=[
  {name:'OPSWAT Cybersecurity Fundamentals Associate',area:'Foundational cybersecurity, infrastructure protection and defensive concepts',why:'Establishes a foundation for understanding security operations.'},
  {name:'CENTRI — Introduction to PowerShell',area:'PowerShell fundamentals and Windows scripting context',why:'Supports interpretation of command activity during endpoint investigations.'},
  {name:'ISC2 Certified in Cybersecurity (CC)',area:'Security principles, access control, network security and incident response',why:'Connects hands-on defensive practice with foundational security concepts.'},
  {name:'Cisco Certified Support Technician (CCST)',area:'Networking / cybersecurity fundamentals — specify the exact CCST track',why:'Reinforces networking and security knowledge relevant to SOC telemetry.'},
  {name:'Fortinet Certified Fundamentals',area:'Cybersecurity fundamentals and network defense',why:'Broadens foundational knowledge of network and security operations.'}
];
const caseGrid=document.getElementById('case-grid');
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
caseGrid.innerHTML=cases.filter(c=>c.id!=='mini-soc').map(c=>`<article class="case-card"><div class="card-meta"><span>${c.number} / OPERATIONAL CASE FILE</span><span class="tag">LAB EXERCISE</span></div><div class="case-symbol" aria-hidden="true">${c.symbol}</div><h3>${escapeHtml(c.title)}</h3><p>${escapeHtml(c.summary)}</p><div class="case-bottom"><span>${c.tools.slice(0,2).map(escapeHtml).join(' / ')}</span><button type="button" class="text-link" data-case="${c.id}" aria-label="Open ${escapeHtml(c.title)} case file">VIEW CASE FILE ↗</button></div></article>`).join('');
document.getElementById('cert-grid').innerHTML=certifications.map((c,i)=>`<article class="cert-card"><div class="card-meta"><span>CR-${String(i+1).padStart(3,'0')}</span><span class="tag pending">VERIFY CREDENTIAL</span></div><h3>${escapeHtml(c.name)}</h3><p><strong>Purpose:</strong> ${escapeHtml(c.why)}</p><p><strong>Areas:</strong> ${escapeHtml(c.area)}</p><div class="cert-link">CERTIFICATE / CREDENTIAL URL TO ADD ↗</div></article>`).join('');
const dialog=document.getElementById('case-dialog');const content=document.getElementById('dialog-content');let lastTrigger=null;
function openCase(id,trigger){const c=cases.find(item=>item.id===id);if(!c)return;lastTrigger=trigger;content.innerHTML=`<div class="card-meta" style="margin-top:24px"><span>${escapeHtml(c.number)} / PROJECTS & OPERATIONS</span><span class="tag">LAB / PROJECT</span></div><h2 id="dialog-title" class="dialog-title">${escapeHtml(c.title)}</h2><p class="dialog-intro">${escapeHtml(c.summary)}</p><div class="tech-row">${c.tools.map(t=>`<span>${escapeHtml(t)}</span>`).join('')}</div><div class="dialog-grid"><div class="dialog-block"><h4>01 / WHY I BUILT OR INVESTIGATED THIS</h4><p>${escapeHtml(c.why)}</p></div><div class="dialog-block"><h4>02 / OBJECTIVE</h4><p>${escapeHtml(c.objective)}</p></div><div class="dialog-block"><h4>03 / INVESTIGATIVE WORKFLOW</h4><ul>${c.actions.map(a=>`<li>${escapeHtml(a)}</li>`).join('')}</ul></div><div class="dialog-block"><h4>04 / SKILLS DEVELOPED</h4><p>${escapeHtml(c.skills)}</p></div><div class="dialog-block"><h4>05 / OUTCOME</h4><p>${escapeHtml(c.outcome)}</p></div><div class="dialog-block"><h4>06 / REAL-WORLD RELEVANCE</h4><p>${escapeHtml(c.relevance)}</p></div></div><div class="evidence-box"><h4>07 / EVIDENCE STATUS — PLACEHOLDERS</h4><p>${escapeHtml(c.evidence)} No URLs or screenshots were supplied, so these are not clickable until verified assets are added.</p><div class="snapshot"><div><strong>▧ INVESTIGATION SNAPSHOT</strong><small>REPLACE WITH A REAL, REDACTED SCREENSHOT</small></div></div><div class="evidence-links"><span>GITHUB REPOSITORY — ADD URL</span><span>SCREENSHOTS — ADD FILES</span><span>WRITE-UP — ADD URL</span><span>DEMO — ADD URL</span><span>TECHNICAL DOCUMENTATION — ADD URL</span></div></div>`;dialog.showModal();}
document.addEventListener('click',e=>{const trigger=e.target.closest('[data-case]');if(trigger)openCase(trigger.dataset.case,trigger);});document.querySelector('.close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('close',()=>lastTrigger?.focus());
const menu=document.querySelector('.menu-toggle'),links=document.querySelector('.nav-links');menu.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close menu':'Open menu');menu.textContent=open?'✕':'☰'});links.addEventListener('click',e=>{if(e.target.closest('a')){links.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='☰';menu.setAttribute('aria-label','Open menu')}});
